import os
import sys
from datetime import datetime

sum = 0.0
fcount = 0
fvalidcount = 0

for fname in os.listdir('.'):
	fcount += 1
	start = fname.find('$') + 1

	# If the file name starts with '_sum' it's a sum file generated by this program; ignore
	if fname.startswith("_sum"):
		continue

	# If we cannot find '$', this is not a valid receipt, continue to next file
	if start == 0:
		print("*** File \"", fname ,"\" doesn't have \'$\' !!!")
		continue

	end = fname.rfind('.')
	fvalidcount += 1
	sum += float(fname[start:end])
	sum = round(sum, 2)
	if (len(sys.argv) > 1 and sys.argv[1] == "debug"):
		print(fname, ":", fname[start:end], ";", float(fname[start:end]), ";", sum)

print(datetime.now())
print("Total number of files", fcount, "; total valid", fvalidcount)
print("Total amount is $", sum)

#Create a sum file
sumfilename = "_sum_"+ "$" + str(sum) + "_" + str(datetime.now()) + ".txt"
#print(sumfilename)
sumfilename = sumfilename.replace(':', '.')
#print(sumfilename)
f = open(sumfilename, "w+")
f.write("Total number of files %d; total valid %d\n" % (fcount, fvalidcount) )
f.write("Total amount is $%.2f" % sum)
f.close()